api_platform:
  title: Hello API Platform
  use_symfony_listeners: true
  version: 1.0.0
  defaults:
    stateless: true
    enable_swagger_ui: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
