vich_uploader:
    db_driver: orm

    mappings:
        recette:
            uri_prefix: /images/recette
            upload_destination: '%kernel.project_dir%/public/images/recette'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
