controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login_check
  methods: POST

mes_recettes:
  path: /api/recettes/moi
  methods: GET
  controller: App\Controller\RecetteController::mesRecettes
 
