# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # Configuration par défaut pour les services dans ce fichier
  _defaults:
    autowire: true # Injection automatique des dépendances dans vos services.
    autoconfigure: true # Enregistrement automatique de vos services comme des commandes, abonnés aux événements, etc.

  # Cela permet de rendre les classes dans le répertoire src/ disponibles pour être utilisées comme services
  # Ce qui crée un service pour chaque classe dont le nom complet est le nom de la classe
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Configuration explicite pour l'écouteur d'événement PasswordEncoderSubscriber
  App\Events\PasswordEncoderSubscriber:
    arguments:
      $passwordHasher: '@security.password_hasher'
    tags:
      - { name: "kernel.event_subscriber" }
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
