parameters:

services:
  # Configuration par défaut pour les services dans ce fichier
  _defaults:
    autowire: true # Injection automatique des dépendances dans vos services.
    autoconfigure: true # Enregistrement automatique de vos services comme des commandes, abonnés aux événements, etc.

  # Cela permet de rendre les classes dans le répertoire src/ disponibles pour être utilisées comme services
  # Ce qui crée un service pour chaque classe dont le nom complet est le nom de la classe
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Configuration explicite pour l'écouteur d'événement PasswordEncoderSubscriber
  App\Events\PasswordEncoderSubscriber:
    arguments:
      $passwordHasher: "@security.password_hasher"
    tags:
      - { name: "kernel.event_subscriber" }

  App\Encoder\MultipartDecoder:
    tags: ["serializer.encoder"]

  App\Serializer\UploadedFileDenormalizer:
    tags: ["serializer.normalizer"]
